name: "Setup VMess Proxy"
description: "Start a v2ray VMess proxy in GitHub Actions using a user-supplied config.json, with optional IP & latency test"
inputs:
  config-path:
    description: "Path to v2ray config.json"
    required: false
    default: "config.json"
  test:
    description: |
      If empty or not set, do not test.
      If set to "true", use https://www.google.com as the default test URL.
      If set to a custom URL (e.g., "https://www.bing.com"), use that for latency test.
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Download v2ray-core
      shell: bash
      run: |
        wget https://github.com/v2fly/v2ray-core/releases/latest/download/v2ray-linux-64.zip > /dev/null
        unzip v2ray-linux-64.zip -d v2ray > /dev/null
        chmod +x v2ray/v2ray
    - name: Start v2ray
      shell: bash
      run: |
        nohup ./v2ray/v2ray run  -c ${{ inputs.config-path }} > v2ray.log 2>&1 & 
        sleep 10
    - name: Check v2ray started
      shell: bash
      run: |
        for i in {1..10}; do
          if pgrep -f "v2ray" > /dev/null; then
            echo "v2ray started successfully."
            exit 0
          fi
          echo "Waiting for v2ray to start..."
          sleep 3
        done
        echo "v2ray failed to start."
        cat v2ray.log || true
        exit 100
    - name: Export Proxy Env
      shell: bash
      run: |
        echo "http_proxy=socks5://127.0.0.1:10808" >> $GITHUB_ENV
        echo "https_proxy=socks5://127.0.0.1:10808" >> $GITHUB_ENV
    - name: Test Outbound IP and Latency (via proxy)
      if: ${{ inputs.test != '' }}
      shell: bash
      run: |
        test_url="${{ inputs.test }}"
        if [[ "$test_url" == "true" ]]; then
          test_url="https://www.google.com"
        fi
        ip=$(curl --socks5 127.0.0.1:10808 -s https://api.ip.sb/ip || curl --socks5 127.0.0.1:10808 -s https://ifconfig.me)
        latency=$(curl --socks5 127.0.0.1:10808 -o /dev/null -s -w "%{time_starttransfer}" "$test_url" || echo "Fail")
        echo "Proxy Test Result: Public IP: $ip | Latency (TTFB to $test_url): $latency s"
